"""edit_guests_table

Revision ID: ffb2f7a44a76
Revises: xkgp7u2k8nso
Create Date: 2023-09-11 15:49:10.540129

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ffb2f7a44a76'
down_revision = 'xkgp7u2k8nso'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guests_test', 'number')
    op.add_column('guests_test', sa.Column('email',sa.String()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guests_test', 'email')
    op.add_column('guests_test', sa.Column('number',sa.String()))
    # ### end Alembic commands ###
